# .appspec.yml

# ... here be your existing CodeDeploy configuration.

# This section controls the action:
branch_config:
    wip\/.*: ~

    '.*':
        deploymentGroupName: codedeploydemo
        deploymentGroupConfig:
            serviceRoleArn: arn:aws:iam::176804238562:role/CodeDeployServiceRole
            ec2TagFilters:
                - { Type: KEY_AND_VALUE, Key: name, Value: terraform-asg-drr }
        deploymentConfig:
            autoRollbackConfiguration:
                #enabled: true

    '.*www':
        deploymentGroupName: $BRANCH.staging.acme.tld
        deploymentGroupConfig:
            serviceRoleArn: arn:aws:iam::176804238562:role/CodeDeployServiceRole
            ec2TagFilters:
                - { Type: KEY_AND_VALUE, Key: hostname, Value: phobos.stage }
